version: "3"
services:
    m65:
        image: phantom-node
        build:
            context: .
        container_name: m65
        volumes:
            - ../../:/root/app/
            - node_modules:/root/app/node_modules
        working_dir: /root/app/
        command: ./examples/docker/start.sh
volumes:
    node_modules:
