version: "3"
services:
    m65-1:
        image: phantom-node
        build:
            context: .
        container_name: m65-1
        volumes:
            - ./:/root/app/
            - node_modules:/root/app/node_modules
        working_dir: /root/app/
        command: ./start.sh
volumes:
    node_modules:
